# Tests for the use_flexstanr() setup helper. These operate on a throwaway
# fixture DESCRIPTION so nothing touches a real project.

make_fixture_pkg <- function(dir, remotes = NULL, imports = NULL) {
  lines <- c(
    "Package: hostpkg",
    "Title: A Host",
    "Version: 0.0.1"
  )
  if (!is.null(imports)) {
    lines <- c(lines, "Imports:", paste0("    ", imports))
  }
  if (!is.null(remotes)) {
    lines <- c(lines, paste0("Remotes:\n    ", remotes))
  }
  writeLines(lines, file.path(dir, "DESCRIPTION"))
  dir
}

# Read a NAMESPACE's directives by parsing it (it is valid R), rather than
# matching its text. roxygen2 >= 8.1.0 emits ONE multi-line importFrom() per
# package instead of one single-line directive per symbol, so a line-wise grep
# for "importFrom(flexstanr,stan_options)" fails against a namespace that is
# still correct. Parsing is agnostic to how the directives are laid out.
# Returns a list of character vectors, one per directive name, e.g.
# `$export` and `$importFrom$flexstanr`.
namespace_symbols <- function(ns_file, directive, from = NULL) {
  calls <- as.list(parse(ns_file))
  hits <- Filter(function(e) {
    is.call(e) && identical(as.character(e[[1L]]), directive)
  }, calls)
  args <- lapply(hits, function(e) as.character(as.list(e)[-1L]))
  if (!is.null(from)) {
    args <- lapply(Filter(function(a) identical(a[[1L]], from), args), `[`, -1L)
  }
  unlist(args, use.names = FALSE)
}

test_that("use_flexstanr adds flexstanr to Imports and records no Remotes by default", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)

  expect_identical(use_flexstanr(path = dir), dir)

  d <- desc::desc(file = file.path(dir, "DESCRIPTION"))
  deps <- d$get_deps()
  expect_true("flexstanr" %in% deps$package[deps$type == "Imports"])
  # CRAN case: no Remotes entry unless a remote is requested.
  expect_length(d$get_remotes(), 0L)
})

test_that("use_flexstanr does not add a Stan backend", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)

  use_flexstanr(path = dir)

  # flexstanr requires neither backend; the host declares its own.
  deps <- desc::desc(file = file.path(dir, "DESCRIPTION"))$get_deps()
  expect_false("rstan" %in% deps$package)
  expect_false("cmdstanr" %in% deps$package)
})

test_that("min_version = NULL pins flexstanr to the installed version", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)

  use_flexstanr(path = dir)

  d <- desc::desc(file = file.path(dir, "DESCRIPTION"))
  deps <- d$get_deps()
  installed <- as.character(utils::packageVersion("flexstanr"))
  expect_identical(deps$version[deps$package == "flexstanr"], paste0(">= ", installed))
})

test_that("min_version accepts an explicit version, and FALSE drops the constraint", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)
  use_flexstanr(path = dir, min_version = "0.1.0")
  d <- desc::desc(file = file.path(dir, "DESCRIPTION"))
  deps <- d$get_deps()
  expect_identical(deps$version[deps$package == "flexstanr"], ">= 0.1.0")

  dir2 <- withr::local_tempdir()
  make_fixture_pkg(dir2)
  use_flexstanr(path = dir2, min_version = FALSE)
  d2 <- desc::desc(file = file.path(dir2, "DESCRIPTION"))
  deps2 <- d2$get_deps()
  expect_identical(deps2$version[deps2$package == "flexstanr"], "*")
})

test_that("use_flexstanr does not clobber an existing rstan version constraint", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir, imports = "rstan (>= 2.18.1)")

  use_flexstanr(path = dir)

  d <- desc::desc(file = file.path(dir, "DESCRIPTION"))
  deps <- d$get_deps()
  expect_identical(deps$version[deps$package == "rstan"], ">= 2.18.1")
})

test_that("a non-NULL remote records a Remotes entry for off-CRAN installs", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)

  use_flexstanr(path = dir, remote = "ACCIDDA/flexstanr")

  d <- desc::desc(file = file.path(dir, "DESCRIPTION"))
  expect_true("ACCIDDA/flexstanr" %in% d$get_remotes())
  expect_true("flexstanr" %in% d$get_deps()$package)
})

test_that("use_flexstanr errors when there is no DESCRIPTION", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  expect_error(use_flexstanr(path = dir), "no DESCRIPTION found")
})

# --- generated re-export file (#26) ------------------------------------------

test_that("flexstanr_reexport_source() carries a do-not-edit banner and the reexport idiom", {
  src <- flexstanr_reexport_source()
  expect_match(src, "Generated by flexstanr")
  expect_match(src, "do not edit by hand")
  # backend entry points imported for internal use ...
  expect_match(src, "@importFrom flexstanr fit_model")
  expect_match(src, "backend_has_draws")
  # ... and the public constructor re-exported (dplyr-style bare reexport)
  expect_match(src, "@importFrom flexstanr stan_options")
  expect_match(src, "@export")
  expect_match(src, "flexstanr::stan_options", fixed = TRUE)
})

test_that("every exported backend accessor is imported into generated host files", {
  # A new backend_*() export has to be added to the internal-import list too, or
  # a host that regenerates its setup file still can't call it unqualified.
  accessors <- grep("^backend_", getNamespaceExports("flexstanr"), value = TRUE)
  expect_true(all(accessors %in% .flexstanr_internal_imports))
  src <- flexstanr_reexport_source()
  for (fn in accessors) expect_match(src, fn, fixed = TRUE)
})

test_that("use_flexstanr() writes the generated re-export file, and reexport = FALSE skips it", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)
  use_flexstanr(path = dir)
  f <- file.path(dir, "R", "flexstanr.R")
  expect_true(file.exists(f))
  expect_match(paste(readLines(f), collapse = "\n"), "flexstanr::stan_options", fixed = TRUE)

  dir2 <- withr::local_tempdir()
  make_fixture_pkg(dir2)
  use_flexstanr(path = dir2, reexport = FALSE)
  expect_false(file.exists(file.path(dir2, "R", "flexstanr.R")))
})

# --- fixture pseudo-package: does the generated file actually export? (#27) ---

test_that("a fixture package generated by use_flexstanr() re-exports stan_options", {
  skip_if_not_installed("desc")
  skip_if_not_installed("roxygen2")
  skip_if_not_installed("pkgload")

  dir <- withr::local_tempdir()
  writeLines(c(
    "Package: reexportfix",
    "Version: 0.0.0.9000",
    "Title: Fixture",
    "Description: Throwaway package exercising flexstanr re-export generation.",
    "License: MIT",
    "Encoding: UTF-8",
    "Roxygen: list(markdown = TRUE)",
    "RoxygenNote: 7.3.3"
  ), file.path(dir, "DESCRIPTION"))

  use_flexstanr(path = dir)

  # generated @export / @importFrom tags -> NAMESPACE (read by parsing, so this
  # holds for either roxygen2 importFrom layout; see namespace_symbols()).
  suppressMessages(roxygen2::roxygenise(dir, roclets = "namespace"))
  ns_file <- file.path(dir, "NAMESPACE")
  expect_true("stan_options" %in% namespace_symbols(ns_file, "export"))
  expect_true(
    "stan_options" %in% namespace_symbols(ns_file, "importFrom", from = "flexstanr")
  )
  # the internal-use entry points are imported but NOT re-exported
  imported <- namespace_symbols(ns_file, "importFrom", from = "flexstanr")
  expect_true(all(c("fit_model", "backend_extract") %in% imported))
  expect_false("fit_model" %in% namespace_symbols(ns_file, "export"))

  # ... and the re-export actually resolves to flexstanr's function
  suppressMessages(pkgload::load_all(dir, quiet = TRUE))
  withr::defer(pkgload::unload("reexportfix"))
  expect_identical(
    get("stan_options", envir = asNamespace("reexportfix")),
    flexstanr::stan_options
  )
})
