# Tests for the use_flexstanr() setup helper. These operate on a throwaway
# fixture DESCRIPTION so nothing touches a real project.

make_fixture_pkg <- function(dir, remotes = NULL) {
  lines <- c(
    "Package: hostpkg",
    "Title: A Host",
    "Version: 0.0.1",
    "Imports:",
    "    rstan (>= 2.18.1)"
  )
  if (!is.null(remotes)) {
    lines <- c(lines, paste0("Remotes:\n    ", remotes))
  }
  writeLines(lines, file.path(dir, "DESCRIPTION"))
  dir
}

test_that("use_flexstanr adds flexstanr to Imports and an interim Remotes entry", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)

  expect_identical(use_flexstanr(path = dir), dir)

  d <- desc::desc(file = file.path(dir, "DESCRIPTION"))
  deps <- d$get_deps()
  expect_true("flexstanr" %in% deps$package[deps$type == "Imports"])
  expect_true("ACCIDDA/flexstanr" %in% d$get_remotes())
})

test_that("use_flexstanr does not clobber an existing rstan version constraint", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)

  use_flexstanr(path = dir)

  d <- desc::desc(file = file.path(dir, "DESCRIPTION"))
  deps <- d$get_deps()
  expect_identical(deps$version[deps$package == "rstan"], ">= 2.18.1")
})

test_that("on_cran = TRUE skips the interim Remotes entry", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)

  use_flexstanr(path = dir, on_cran = TRUE)

  d <- desc::desc(file = file.path(dir, "DESCRIPTION"))
  expect_false("ACCIDDA/flexstanr" %in% d$get_remotes())
  expect_true("flexstanr" %in% d$get_deps()$package)
})

test_that("use_flexstanr errors when there is no DESCRIPTION", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  expect_error(use_flexstanr(path = dir), "no DESCRIPTION found")
})

# --- generated re-export file (#26) ------------------------------------------

test_that("flexstanr_reexport_source() carries a do-not-edit banner and the reexport idiom", {
  src <- flexstanr_reexport_source()
  expect_match(src, "Generated by flexstanr")
  expect_match(src, "do not edit by hand")
  # backend entry points imported for internal use ...
  expect_match(src, "@importFrom flexstanr fit_model")
  expect_match(src, "backend_has_draws")
  # ... and the public constructor re-exported (dplyr-style bare reexport)
  expect_match(src, "@importFrom flexstanr stan_options")
  expect_match(src, "@export")
  expect_match(src, "flexstanr::stan_options", fixed = TRUE)
})

test_that("use_flexstanr() writes the generated re-export file, and reexport = FALSE skips it", {
  skip_if_not_installed("desc")
  dir <- withr::local_tempdir()
  make_fixture_pkg(dir)
  use_flexstanr(path = dir, on_cran = TRUE)
  f <- file.path(dir, "R", "flexstanr.R")
  expect_true(file.exists(f))
  expect_match(paste(readLines(f), collapse = "\n"), "flexstanr::stan_options", fixed = TRUE)

  dir2 <- withr::local_tempdir()
  make_fixture_pkg(dir2)
  use_flexstanr(path = dir2, on_cran = TRUE, reexport = FALSE)
  expect_false(file.exists(file.path(dir2, "R", "flexstanr.R")))
})

# --- fixture pseudo-package: does the generated file actually export? (#27) ---

test_that("a fixture package generated by use_flexstanr() re-exports stan_options", {
  skip_if_not_installed("desc")
  skip_if_not_installed("roxygen2")
  skip_if_not_installed("pkgload")

  dir <- withr::local_tempdir()
  writeLines(c(
    "Package: reexportfix",
    "Version: 0.0.0.9000",
    "Title: Fixture",
    "Description: Throwaway package exercising flexstanr re-export generation.",
    "License: MIT",
    "Encoding: UTF-8",
    "Roxygen: list(markdown = TRUE)",
    "RoxygenNote: 7.3.3"
  ), file.path(dir, "DESCRIPTION"))

  use_flexstanr(path = dir, on_cran = TRUE)

  # generated @export / @importFrom tags -> NAMESPACE
  suppressMessages(roxygen2::roxygenise(dir, roclets = "namespace"))
  ns <- readLines(file.path(dir, "NAMESPACE"))
  expect_true(any(grepl("export(stan_options)", ns, fixed = TRUE)))
  expect_true(any(grepl("importFrom(flexstanr,stan_options)", ns, fixed = TRUE)))

  # ... and the re-export actually resolves to flexstanr's function
  suppressMessages(pkgload::load_all(dir, quiet = TRUE))
  withr::defer(pkgload::unload("reexportfix"))
  expect_identical(
    get("stan_options", envir = asNamespace("reexportfix")),
    flexstanr::stan_options
  )
})
