# flexstanr's consumer-facing surface, kept in ONE place so the generated
# re-export file (and its test) stay in lockstep with the public API.
#   reexports: the host re-exports these, so `host::fn()` keeps working for its
#              users (e.g. `imuGAP::stan_options()`).
#   internal_imports: the host imports these for its own internal calls; they are
#              NOT re-exported (users reach them through flexstanr, or the host's
#              own wrappers).
.flexstanr_reexports <- "stan_options"
.flexstanr_internal_imports <- c(
  "fit_model", "backend_draws_array", "backend_extract",
  "backend_generate_quantities", "backend_has_draws"
)

# Wrap names into `#' @importFrom flexstanr a b c` lines, at most `per_line` names
# each, so no generated line trips roxygen/lintr length limits.
.importfrom_lines <- function(names, per_line = 3L) {
  groups <- split(names, (seq_along(names) - 1L) %/% per_line)
  vapply(
    groups,
    function(g) paste("#' @importFrom flexstanr", paste(g, collapse = " ")),
    character(1)
  )
}

#' Generate a host package's flexstanr re-export file
#'
#' @description Returns the text that [use_flexstanr()] writes to the host's
#' `R/flexstanr.R`. It carries a do-not-edit banner (the file is generated, in the
#' spirit of a roxygen artifact) and, using the canonical surface lists above,
#' imports flexstanr's backend entry points for internal use and re-exports the
#' public constructor(s) so `host::stan_options()` keeps resolving.
#'
#' Exposed (internal) so the generation can be tested and regenerated
#' independently. See the fixture-package test.
#'
#' @return a single string: the full file contents, banner included.
#' @keywords internal
flexstanr_reexport_source <- function() {
  ver <- tryCatch(
    as.character(utils::packageVersion("flexstanr")),
    error = function(e) "dev"
  )
  imports_block <- paste(
    c(.importfrom_lines(.flexstanr_internal_imports), "NULL"),
    collapse = "\n"
  )
  reexport_blocks <- vapply(.flexstanr_reexports, function(fn) {
    paste0(
      "#' @importFrom flexstanr ", fn, "\n",
      "#' @export\n",
      "flexstanr::", fn
    )
  }, character(1))
  paste0(
    "# Generated by flexstanr ", ver, ": do not edit by hand.\n",
    "# Regenerate with flexstanr::use_flexstanr() (updates DESCRIPTION and this file).\n",
    "#\n",
    "# flexstanr provides this package's portable Stan backend: the backend-agnostic\n",
    "# fit / draws / generated-quantities entry points and the sampler-option\n",
    "# constructor, resolving this package's compiled stanmodels automatically. The\n",
    "# fit_model()/backend_* entry points are imported for internal use; only the\n",
    "# constructor(s) below are re-exported as part of this package's public API.\n",
    "\n",
    imports_block, "\n\n",
    paste(reexport_blocks, collapse = "\n\n"), "\n"
  )
}

#' Wire flexstanr into a host package
#'
#' @description
#' A one-time setup helper, in the spirit of usethis's `use_*` functions, that
#' declares flexstanr as a dependency of the host package you run it from. It
#' adds flexstanr (and rstan, the default backend) to the host's `Imports` and,
#' until flexstanr is on CRAN, an interim `Remotes` entry so `remotes` / `pak`
#' can install it from GitHub. It also writes a generated re-export file
#' (`R/flexstanr.R`) so `host::stan_options()` keeps resolving and the host's
#' internal calls to [fit_model()] / the `backend_*` accessors are imported.
#'
#' The re-export file is generated: it carries a do-not-edit banner and is
#' overwritten on each run, so re-run `use_flexstanr()` to pick up changes to
#' flexstanr's re-exported surface. flexstanr resolves the host's own compiled
#' models automatically from the calling package.
#'
#' @param path path to the host package's root (the directory containing its
#'   `DESCRIPTION`). Defaults to the working directory.
#' @param remote the GitHub `owner/repo` used for the interim `Remotes` entry
#'   while flexstanr is pre-CRAN.
#' @param on_cran set `TRUE` once flexstanr is on CRAN to skip the interim
#'   `Remotes` entry; a plain `Imports` dependency is then enough.
#' @param reexport whether to (over)write the generated `R/flexstanr.R` re-export
#'   file. `TRUE` by default; set `FALSE` to only edit `DESCRIPTION`.
#' @param reexport_file path, relative to `path`, of the generated re-export file.
#' @returns the host package `path`, invisibly.
#'
#' @examples
#' \dontrun{
#' # from the root of your Stan package:
#' flexstanr::use_flexstanr()
#' }
#'
#' @export
use_flexstanr <- function(path = ".",
                          remote = "ACCIDDA/flexstanr",
                          on_cran = FALSE,
                          reexport = TRUE,
                          reexport_file = file.path("R", "flexstanr.R")) {
  if (!requireNamespace("desc", quietly = TRUE)) {
    stop(
      "use_flexstanr() needs the 'desc' package to edit DESCRIPTION; ",
      "install it with install.packages('desc').",
      call. = FALSE
    )
  }
  desc_path <- file.path(path, "DESCRIPTION")
  if (!file.exists(desc_path)) {
    stop(
      "no DESCRIPTION found at '", path, "'. Run use_flexstanr() from the root ",
      "of the package you are wiring flexstanr into.",
      call. = FALSE
    )
  }
  d <- desc::desc(file = desc_path)

  # Add flexstanr + the default backend to Imports, but do not clobber an
  # existing rstan version constraint the host already declares.
  have <- d$get_deps()$package
  if (!"flexstanr" %in% have) {
    d$set_dep("flexstanr", "Imports")
  }
  if (!"rstan" %in% have) {
    d$set_dep("rstan", "Imports")
  }

  # Interim Remotes entry so flexstanr installs from GitHub until it is on CRAN.
  if (!isTRUE(on_cran)) {
    remotes <- d$get_remotes()
    if (!remote %in% remotes) {
      d$set_remotes(unique(c(remotes, remote)))
    }
  }

  d$write(file = desc_path)

  # Write the generated re-export file so host::stan_options() keeps resolving and
  # the host's internal fit_model()/backend_* calls are imported. The file is a
  # generated artifact (do-not-edit banner) and is overwritten on each run.
  if (isTRUE(reexport)) {
    out <- file.path(path, reexport_file)
    dir.create(dirname(out), showWarnings = FALSE, recursive = TRUE)
    writeLines(flexstanr_reexport_source(), out)
  }

  invisible(path)
}
